---
# this task is to install some essential apps on the jenkins server
- name: install essentials
  apt:
    pkg:
      - apt-transport-https
      - ca-certificates
      - docker-compose
      - git
      - jq
      - kubectl
      - mysql-client
      - nano
      - openjdk-11-jre
      - python-pytest
      - python3-pip
      - software-properties-common
      - terraform


- name: install cne on the jenkins machine
  pip:
    name:
      - cne>2.10.6,<3.0
